---
title: "Open Neurophysiology"
subtitle: "Neurodynamics"
page-layout: full
search: false
---

+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| # Date | # Day | # Topic                                                                          | # Due            | # Reading Assignments                                                                                                                                                                                                        |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Course  Introduction**                                                   |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 9-Jan  | Tue   | Welcome to Course & Overview                                                     |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 11-Jan | Thu   | Introduction to course objectives, expectations, & assessment                    | Survey Responses | [Rule, A., et al. (2019). Ten simple rules for writing and sharing computational analyses in Jupyter Notebooks. PLOS Comp Biol, 15(7), e1007007. (Link)](https://doi.org/10.1371/journal.pcbi.1007007) \|                    |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Team Formation & Initial Meetings**                                      |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 16-Jan | Tue   | Students form teams based on interest or skill sets.                             |                  | [Garrett-Ruffin, S., et al. (2021). Open science in psychophysiology. Int J Psychophysiology, 162, 69–78. (Link)](https://doi.org/10.1016/j.ijpsycho.2021.02.005) \|                                                         |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 18-Jan | Thu   | Teams hold initial meetings to get acquainted and discuss potential interests.   |                  | [Dogucu, M., & Çetinkaya-Rundel, M. (2022). Tools and Recommendations for Reproducible Teaching. Journal of Statistics and Data Science Education, 30(3), 251–260. (Link)](https://doi.org/10.1080/26939169.2022.2138645) \| |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Workshop: Communication & Collaboration**                                |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 23-Jan | Tue   | Practical session on using tools for collaboration (e.g., Git/Github, Markdown). |                  | [Perez-Riverol, Y., et al. (2016). Ten Simple Rules for Taking Advantage of Git and GitHub. PLOS Comp Biol, 12(7), e1004947. (Link)](https://doi.org/10.1371/journal.pcbi.1004947) \|                                        |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 25-Jan | Thu   | Introduction to effective communication and collaboration in research.           |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Research Goals / Communication Guidelines**                              |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 30-Jan | Tue   | Teams define their research questions/goals.                                     |                  | Ten Simple Rules Series                                                                                                                                                                                                      |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 1-Feb  | Thu   | Teams present their research goals and receive feedback.                         |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Technical Workshops & Skill Assessments**                                |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 6-Feb  | Tue   | Conduct workshops on necessary data science skills (Python, R, data wrangling).  |                  | -[McKinney, W. (2022). Python for data analysis (3rd ed).](https://wesmckinney.com/book/) </br></br> - [Vanderplas, J. T. (2022). Python data science handbook (2nd ed).](https://jakevdp.github.io/PythonDataScienceHandbook/)    |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 8-Feb  | Thu   | Students assess their skills and identify areas for growth.                      |                  | [Wickham, H. (2016). ggplot2 (3rd ed).(link)](https://ggplot2-book.org/)  </br></br> - [Wickham, H., et al. (2023). R for data science (2nd ed).(link)](https://r4ds.hadley.nz/)                                                                                                                       |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Continuation of Skill Building & Application**                           |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 13-Feb | Tue   | Teams apply learned skills to their projects.                                    |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 15-Feb | Thu   | Peer-to-peer skill sharing sessions.                                             |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Preparing First Presentation**                                           |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 20-Feb | Tue   | Teams work on their initial project.                                             |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 22-Feb | Thu   | Focus: methodologies & data analysis.                                            |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Presentation of Initial Findings**                                       |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 27-Feb | Tue   | Each team presents their initial findings.                                       |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 29-Feb | Thu   | Peer and instructor feedback session.                                            |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Feedback Incorporation & Project Adjustment**                            |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 5-Mar  | Tue   | Teams reevaluate their goals and methods based on feedback.                      |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 7-Mar  | Thu   | Revise project plans and strategies.                                             |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 11-Mar |       | Spring Break                                                                     |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Deep Dive into Revised Projects**                                        |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 18-Mar | Tue   | Feedback Incorporation and Project Adjustment                                    |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 20-Mar | Thu   | Focus on overcoming challenges and leveraging strengths.                         |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Poster Creation & Presentation Skills**                                  |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 26-Mar | Tue   | Introduction to creating academic posters and effective presentation skills.     |                  | Ten Simple Rules Series                                                                                                                                                                                                      |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 28-Mar | Thu   | Begin creating posters for their projects.                                       |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Practice and Refinement of Presentations**                               |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 2-Apr  | Tue   | Mock presentations and feedback sessions.                                        |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 4-Apr  | Thu   | Finalize posters and practice for outside presentations.                         |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Finalizing Projects**                                                    |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 9-Apr  | Tue   | Final push to complete projects.                                                 |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 11-Apr | Thu   | Focus on polishing analysis, conclusions, and presentation.                      |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Final Presentations & Peer Review**                                      |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 16-Apr | Tue   | Teams present their final projects to the class and invited guests.              |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 18-Apr | Thu   | Conduct a peer review & feedback.                                                |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|        |       | ##### **Reflective Discussions & Course Feedback**                               |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| 23-Apr | Tue   | Celebration. Teams discuss what they learned, challenges, & accomplishments.     |                  |                                                                                                                                                                                                                              |       |
+--------+-------+----------------------------------------------------------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
