---
title: "Useful Links"
---

### Models of Dynamical Systems

- [Mesoscopic Brain Dynamics](http://www.scholarpedia.org/article/Mesoscopic_brain_dynamics)
- [System Dynamics Interactive Simulations ](https://www.complexity-explorables.org/explorables/)
- [Kuramoto Model: Weakly Coupled Oscillators](https://en.wikipedia.org/wiki/Kuramoto_model)
- ["Scale-free" Dynamics and Complexity](http://www.scholarpedia.org/article/Scale-free_neocortical_dynamics)
- [1/f Noise](http://www.scholarpedia.org/article/1/f_noise)

### Free Books for Python or R

- [https://wesmckinney.com/book/](https://wesmckinney.com/book/)
- [https://r4ds.hadley.nz/](https://r4ds.hadley.nz/)
- [https://jakevdp.github.io/PythonDataScienceHandbook/](https://jakevdp.github.io/PythonDataScienceHandbook/)
- [https://ggplot2-book.org/](https://ggplot2-book.org/)
- [https://crumplab.com/Books.html](https://crumplab.com/Books.html)
- [https://github.com/christophergandrud/Rep-Res-Book](https://github.com/christophergandrud/Rep-Res-Book)
- [https://merely-useful.tech/py-rse/](https://merely-useful.tech/py-rse/)
- [https://merely-useful.tech/r-rse/](https://merely-useful.tech/r-rse/)

#### Data Science Courses

- [https://merely-useful.tech/novice-r/](https://merely-useful.tech/novice-r/)
- [https://github.com/merely-useful/novice-py/](https://github.com/merely-useful/novice-py/)
- [https://github.com/merely-useful/py-rse](https://github.com/merely-useful/py-rse)

#### Open Science
Starting points for learning about accessibility

- [https://quarto.org/](https://quarto.org/) 
- [https://voltrondata.com/labs](https://voltrondata.com/labs)
- [https://carpentries.org/](https://carpentries.org/)
- [https://www.cos.io/products/osf](https://www.cos.io/products/osf)
- [https://ropensci.org](https://ropensci.org) 
- [https://posit.co/products/enterprise/academy/](https://posit.co/products/enterprise/academy/) 
- [https://www.datacamp.com](https://www.datacamp.com)

#### Shared Docs with links to more information:
- [https://github.com/asoplata/open-science-resources](https://github.com/asoplata/open-science-resources) 
- [https://github.com/asoplata/open-computational-neuroscience-resources](https://github.com/asoplata/open-computational-neuroscience-resources) 

#### Open Science Pre-publication Sites:
- [https://neurolibre.org](https://neurolibre.org) 
- [https://psyarxiv.com](https://psyarxiv.com)
- [https://osf.io/preprints/](https://osf.io/preprints/) 
- [https://arxiv.org](https://arxiv.org)



- [Carpentries Tutorial: Introduction to Reproducible Publications with RStudio](https://carpentries-incubator.github.io/Reproducible-Publications-with-RStudio/aio/index.html)

#### Interesting links
- [Two-minute Neuroscience: ketamine](https://youtu.be/kRtNsaMildw)

### Neuroscience Information

- [Neurodata Without Borders](https://www.nwb.org/)
- [Brain Imaging Data Structure (BIDS)](https://bids.neuroimaging.io/)
- [Carpentries: Working with MRI Data in Python](https://carpentries-incubator.github.io/SDC-BIDS-IntroMRI/)
- [Carpentries: Functional Neuroimaging Analysis in Python](https://carpentries-incubator.github.io/SDC-BIDS-fMRI/)
- [International Conference on Neuroinformatics (ICNF)](https://www.incf.org/)
   - [ICNF: Using Training Resources](https://training.incf.org/how-to-use)
   - [ICNF: *tutorial search*](https://training.incf.org/search)
- [NeuroStars](https://neurostars.org/)
- [NeuroHack Academy](https://neurohackademy.org/apply/)
- [NeuroMatch Academy](https://academy.neuromatch.io/courses)
- [Concepts in Cognitive: Ontological/Taxonomy](https://www.cognitiveatlas.org/)

DataCamp Cheasheets:

https://www.datacamp.com/tutorial/coding-best-practices-and-guidelines

https://www.datacamp.com/cheatSheet/bash-and-zsh-shell-terminal-basics-cheat-sheet 

https://www.datacamp.com/cheatSheet/quarto-cheat-sheet-previously-known-as-r-markdown

https://www.datacamp.com/cheatSheet/the-generative-ai-tools-landscape

https://www.datacamp.com/cheatSheet/reshaping-data-with-pandas-in-python. 

https://www.datacamp.com/cheatSheet/text-data-in-python-cheat-sheet 


https://www.datacamp.com/cheatSheet/working-with-dates-and-times-in-python-cheat-sheet

https://www.datacamp.com/cheatSheet/python-seaborn-cheat-sheet

https://www.datacamp.com/cheatSheet/scipy-cheat-sheet-linear-algebra-in-python

https://www.datacamp.com/cheatSheet/pandas-cheat-sheet-data-wrangling-in-python

https://www.datacamp.com/cheatSheet/jupyter-notebook-cheat-sheet

https://www.datacamp.com/cheatSheet/matplotlib-cheat-sheet-plotting-in-python

https://www.datacamp.com/cheatSheet/getting-started-with-python-cheat-sheet

https://www.datacamp.com/tutorial/a-beginners-guide-to-chatgpt-api

https://www.datacamp.com/tutorial/r-markdown-tutorial

https://www.datacamp.com/tutorial/what-is-a-confusion-matrix-in-machine-learning

https://www.datacamp.com/tutorial/what-is-hugging-face

https://www.datacamp.com/tutorial/coding-best-practices-and-guidelines

https://www.datacamp.com/tutorial/introduction-to-data-pipelines-for-data-professionals

https://www.datacamp.com/tutorial/a-data-scientists-guide-to-signal-processing

https://www.datacamp.com/tutorial/seeing-like-a-machine-a-beginners-guide-to-image-analysis-in-machine-learning

https://www.datacamp.com/tutorial/introduction-to-convolutional-neural-networks-cnns

https://www.datacamp.com/tutorial/pytorch-vs-tensorflow-vs-keras



https://www.datacamp.com/tutorial/the-cross-entropy-loss-function-in-machine-learning

https://viso.ai/deep-learning/pytorchvideo-video-understanding/

https://www.simplilearn.com/best-ai-tools-for-video-editing-article



AmadeusGPT: a natural language interface for interactive animal behavioral analysis
https://neurips.cc/media/PosterPDFs/NeurIPS%202023/72610.png?t=1701780014.8377924
 

https://pytorch.org/audio/stable/index.html

https://pytorch.org/vision/stable/index.html


Torchvision
https://paperswithcode.com/lib/torchvision#:~:text=torchvision-,The%20torchvision%20library%20consists%20of%20popular%20datasets%2C%20model%20architectures%2C%20and,video%20classification%20and%20semantic%20segmentation.

State of the Art
https://paperswithcode.com/sota

https://paperswithcode.com/libraries

https://paperswithcode.com/methods


https://github.com/huggingface/transformers

https://huggingface.co/docs/transformers/index


Cran-R Task Views

R Task Views: Tracking Data 
https://cran.r-project.org/web/views/Tracking.html 
Carpentries
https://datacarpentry.org/rr-version-control/02-git-in-github/index.html



Ten Simple Rules Collection




https://www.reddit.com/r/bioinformatics/comments/12puflj/plos_computational_biology_ten_simple_rules_papers/?rdt=36960

PLOS Computational Biology: filter “undergraduate”
https://journals.plos.org/ploscompbiol/search?filterJournals=PLoSCompBiol&filterSubjects=Undergraduates&q=

PLOS Computational Biology: filter “graduate”


Historical Research

Computational Historical Thinking: With Applications in R
Lincoln A. Mullen
https://dh-r.lincolnmullen.com/







