---
title: Misophonia Project
---

# Overview

## What is misophonia?

Also, known as selective sound sensitivity syndrome or sound-rage, misophonia is a disorder in which certain sounds trigger emotional or physiological responses that some might perceive as unreasonable given the circumstance. Those who have misophonia might describe it as when a sound “drives you crazy.” Their reactions can range from anger and annoyance to panic and the need to flee.

- [Misophonia on Wikipedia](https://en.wikipedia.org/wiki/Misophonia)

- Ward, R. T., Gilbert, F. E., Pouliot, J., Chiasson, P., McIlvanie, S., Traiser, C., ... & Keil, A. (2022). The Relationship Between Self-Reported Misophonia Symptoms and Auditory Aversive Generalization Leaning: A Preliminary Report. Frontiers in Neuroscience, 16, 899476. [https://doi.org/10.3389/fnins.2022.899476](https://doi.org/10.3389/fnins.2022.899476)
- Farkas, A. H., Ward, R. T., Gilbert, F. E., Pouliot, J., Chiasson, P., McIlvanie, S., ... & Keil, A. (2023). Auditory Aversive Generalization Learning Prompts Threat-Specific Changes in Alpha-Band Activity. bioRxiv, 2023-12. [https://doi.org/10.1101/2023.12.04.569971](https://doi.org/10.1101/2023.12.04.569971)
- **Accepted Pre-registration**: Ward, R., Keil, A., Pouliot, J., Mears, R. P., Chiasson, P., & McIlvanie, S. (2021, September 27). Psychophysiological mechanisms underlying aversive conditioning in Misophonia.[https://doi.org/10.17605/OSF.IO/E26AD](https://doi.org/10.17605/OSF.IO/E26AD)

- [Misophonia: Zotero Refs](https://www.zotero.org/groups/2418504/uf-ephys-misophonia/library)

### Related concept (but not the same phenomenon)

ASMR (Autonomous sensory meridian response) is a tingling sensation that typically begins on the scalp and moves down the back of the neck and upper spine. A pleasant form of paresthesia, it has been compared with auditory-tactile synesthesia and may overlap with frisson.

### Auditory Steady-State Response

- Brugge, J. F., Nourski, K. V., Oya, H., Reale, R. A., Kawasaki, H., Steinschneider, M., & Howard III, M. A. (2009). Coding of repetitive transients by auditory cortex on Heschl's gyrus. Journal of neurophysiology, 102(4), 2358-2374. [https://doi.org/10.1152/jn.91346.2008](https://doi.org/10.1152/jn.91346.2008)

- Popov, T., Oostenveld, R., & Schoffelen, J. M. (2018). FieldTrip made easy: an analysis protocol for group analysis of the auditory steady state brain response in time, frequency, and space. Frontiers in neuroscience, 12, 711.[https://doi.org/10.3389/fnins.2018.00711](https://doi.org/10.3389/fnins.2018.00711)

- Pantev, C., Roberts, L. E., Elbert, T., Roβ, B., & Wienbruch, C. (1996). Tonotopic organization of the sources of human auditory steady-state responses. Hearing research, 101(1-2), 62-74.[]()

- Parker, D. A., Hamm, J. P., McDowell, J. E., Keedy, S. K., Gershon, E. S., Ivleva, E. I., ... & Clementz, B. A. (2019). Auditory steady-state EEG response across the schizo-bipolar spectrum. Schizophrenia research, 209, 218-226. [https://doi.org/10.1016/j.schres.2019.04.014](https://doi.org/10.1016/j.schres.2019.04.014)


### MNE-Python Workflow (Schematic)

```{mermaid, echo=FALSE, warning=FALSE, message=FALSE}

%%{init: {'theme':'forest'}}%%

graph LR;
        subgraph Sensor-level-analysis

       A[Decode time-by-time </br>  using a 'sliding' estimator] --> B[Time-frequency </br> decomposition] 
       B --> C[Decoding </br> based on </br> common spatial patterns] 
       C --> D[Noise covariance </br> estimation] 
       D --> E[Group average </br> at the </br> sensor level] 
   end
  
    subgraph Preprocessing

       l1[Assess </br> channel-wise </br> data quality] --> l2[Estimate </br> head positions] 
       l2 --> l3[Apply low- and </br> high-pass filters] 
       l3 --> l4[Temporal regression </br> for artifact removal]
       l4 --> l5a[Fit ICA] 
       l5a --> l6a[Find ICA </br> artifacts] 
       l4 --> l5b[Extract epochs] 
       l5b --> l7[Apply ICA] 
       l6a --> l7 --> l8[Remove epochs </br> based on  </br> PTP amplitudes]  
       l5b --> l6b[Apply SSP] 
       l4 --> l5c[Compute SSP] 
       l5c --> l6b[Apply SSP] 
       l6b --> l8[Remove epochs </br> based on </br> PTP amplitudes] 
       l8 --> l9[Extract </br> evoked data for </br> each condition] 
       l9 --> l10[Decode pairs of </br>  conditions based on </br> entire epochs] 
    end
    

   
   %%l0[Raw Data] --> l1
   %%E --> F[Output </br> Statistical </br> Analysis Pipeline]    
   
   classDef green fill:#9f6,stroke:#333,stroke-width:0.5px;
   classDef orange fill:#f96,stroke:#333,stroke-width:1px;
   classDef white fill:#fff,stroke:#333,stroke-width:1px;
   classDef sq stroke:#f66,stroke-width:1px;
   classDef blue fill:#6699cc,stroke:#333,stroke-width:1px;
   classDef red fill:#D32737,stroke:#FFF,stroke-width:1.5px;
     
   class Preprocessing,Sensor-level-analysis white

```

::: columns
::: {.column width="50%"}

<https://github.com/mne-tools>

::: 
::: {.column width="50%"}

<https://mne.tools/stable/index.html>


:::
:::


### MNE-Python

- [MNE-Python](https://mne.tools/stable/index.html) is a Python package for MEG and EEG data analysis.

### MNE-BIDS

- [MNE-BIDS](https://mne.tools/mne-bids/stable/index.html) is a Python package for converting data from the Brain Imaging Data Structure (BIDS) format to MNE-Python format.

- [BIDS](https://bids.neuroimaging.io/) (Brain Imaging Data Structure) A simple and intuitive way to organize and describe your neuroimaging and behavioral data.

### MNE-BIDS-Pipeline   

- [MNE-BIDS-Pipeline](https://mne.tools/mne-bids-pipeline/stable/index.html) is a full-flegded processing pipeline Python package for preprocessing MEG and EEG data.





### Finding things on HiPerGator

- [UF Research Computing Documentation](https://help.rc.ufl.edu/doc/UFRC_Help_and_Documentation)



