---
title: "PGSO Undergraduate Forum Spring 2024: submission due March 20"
author: "RPM"
date: "2024-02-07"
categories: [conferences, abstracts, posters]
---

Here is an email that was sent out about the upcoming poster competition on April 18.

The Psychology Graduate Student Organization (PGSO) will be hosting the Undergraduate Poster Forum once again this Spring!

This PGSO undergraduate poster competition is a time for undergraduates to flex their research muscles and show what they've been working on in their labs over the past year(s). Abstracts (suggested length is 250-300 words) are due no later than Monday, March 20th at 11:59pm EST with the in-person poster session on Thursday, April 18th, from 4-5 pm on the 1st floor of the Psychology building. Posters will be judged by graduate students, with 1st, 2nd, and 3rd place posters receiving an award in the form of a gift card for $75, $50, and $25, respectively. 

Please forward this call for abstracts to interested undergraduate students.
Abstract submission link: [Qualtrics Submission Form](https://ufl.qualtrics.com/jfe/form/SV_cCOLl2uo1Zh7xyu)

Best,

Hugh Farrior, 

MS Graduate Research Assistant, PGSO President  
Neurocognitive Laboratory  
University of Florida  
hugh910f@ufl.edu
