---
title: "Introduction to GitHub for Open Science"
description: "Introduction to Version control for doing open science"
author: "R Mears"
categories: [code, development, organization, version control, slides, tutorial]
date: "7/11/2022"
---

[Open Science With GitHub: An Introduction](https://csea-lab.github.io/github-collaboration-slides/git-collab-slides.html#/title-slide)

## Overview
Much of open science requires some technical knowledge that many novices find to be initially burdensome and confusing. Open source analysis tools are usually a work in progress.  Documentation for these tools, if present at all, will be incomplete or out of date. The purpose of this slideshow is to explore concepts that will enable team coordination on software usage and code development projects. The hope is that users will be able to find the information that they need from development notes and communication between code authors. In the long-term, notes and comments about the intended function, rationale, and usage of code will be useful for outsiders but also for the project organizers and code developers themselves. 

